server:
  host: 0.0.0.0
  port: 9091
  buffers:
    read: 4096
    write: 4096
  path: "authelia"
log:
  level: debug
  file_path: /config/logs/authelia.log
default_redirection_url: https://usama8800.net
authentication_backend:
  password_reset:
    disable: true
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 512
      parallelism: 8
access_control:
  default_policy: deny
  rules:
    - domain:
      - usama8800.net
      - "*.usama8800.net"
      policy: one_factor
session:
  name: authelia_session
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: usama8800.net
  redis:
    host: redis
    port: 6379
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: true
  smtp:
    username: usama8800@gmail.com
    password:
    host: smtp.gmail.com
    port: 587
    sender: usama8800@gmail.com
    subject: "[Authelia] {title}"
    startup_check_address: test@authelia.com
    disable_require_tls: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
